### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by HelloKitty** [FishPhd/DewritoUpdater#2]
The licensing terms you've opted for in this repo would require all forks, with changes, of this repo to be private or otherwise be in violation of: "NoDerivatives - If you remix, transform, or build upon the material, you may not distribute the modified material." 

This discourages collaboration by making forking, committing and generation of a pull-request a violation of license. Even in the cases of a pull request from a private fork it still may be in violation of the license since the pull request itself could be considered a distribution of a derivative.

Additionally, CC themselves recommend against using their licenses for software https://wiki.creativecommons.org/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F

**Comment by UPLYNXED** [comment]
_We know exactly what this license means and why we chose it and we have our reasons._

If you want to collaborate on this application or have a modified version on a public repo, just ask us for permission. 
We're not hardasses, we'll _probably_ let you do what you want to do as long as you're not just shamelessly ripping the source, changing it for your own purposes.

All we need to know is what you intend to do, and that _you know_ that if you violate our trust your permission will be revoked.

Furthermore, this repo is for pushing code around, and for showing people what we're up to. It was not uploaded to github with the intention of allowing other people to do as they see fit with it without our permission. If you have a good contribution, just ask our permission (which you haven't yet) and send a pull request (which you did).
