### ISSUE TITLE
Dewrito Launcher Stopped working

### ISSUE THREAD

**Issue by mccapital** [FishPhd/DewritoUpdater#22]
I have a problem with my halo, i downloaded the game files then copied the launcher and the .json file, i open the launcher and it verifies every thing, then i click update and a Message comes up saying "Dewrito launcher has stopped working" "Looking for solutions' I'm using windows 7, Do you know the cause?

**Comment by SteelSliver** [comment]
The update server sends people broken tags right now, if you updated within the past couple of hours, it will crash the launcher, and break the game. The update server should be fixed within the next 24 hours.

Download the unbroken files here, and next time you launch the DewritoUpdater, press skip https://www.dropbox.com/s/us6nbkm1po30m65/Eldorito0.4.7.zip?dl=0

**Comment by FishPhd** [comment]
https://www.reddit.com/r/HaloOnline/comments/3cvlla/warning_do_not_update/

**Comment by mccapital** [comment]
Thank you

**Comment by mccapital** [comment]
I will update if i have ave any luck :) Thanks for the support

**Comment by mccapital** [comment]
Wait i have the original file in my downloads folder for WinRar that version has not been changed yet can i just download the .json file and the Dewrito Updater again and copy it into that folder, then when i open the launcher press skip?

**Comment by mccapital** [comment]
OK i did the things you told me to do and when i press skips it asks if i want to run the program, i click run then i can see the icon for the game on the task bar for a second and then i disappears, i cant even get in the game, did i do something wrong?

**Comment by mccapital** [comment]
UPDATE: After restarting my computer i was able to get it to work! THANKS!
