### ISSUE TITLE
DewritoUpdater not working on Windows 10

### ISSUE THREAD

**Issue by TheWeion** [FishPhd/DewritoUpdater#25]
I have recently upgraded to Windows 10 and for some reason the Launcher is not working, I have looked at the Event View and I am getting multiple errors including a .NET Runtime error, I have logged them here:

https://forum.halo.click/index.php?/topic/397-dewrito-launcher-not-working-and-fails-reinstallation-on-windows-10/

I have the following Frameworks installed:
v4.6 Full
v4.6 Client
v3.5 SP1
v3.0 SP2
v2.0 SP2

**Comment by twist84** [comment]
I am on windows 10 and I have no problems at all https://imgrush.com/gQMYEM37kjM5.mp4

**Comment by TheWeion** [comment]
Yeah, it does work now, I reinstalled Windows 10.
