### ISSUE TITLE
missing file "maps\fonts\font_package.bin"

### ISSUE THREAD

**Issue by juhoyhoy** [FishPhd/DewritoUpdater#32]
after spending over an hour trying to validate my files in the launcher, i decided to try a force uodate from the launcher, then its tell me im missing, "maps\fonts\font_package.bin"
im not really sure what to do about this

**Comment by scooterpsu** [comment]
This is actually an issue with the update server, not the updater itself. The file is fine, but the hash it's comparing to isn't, so it can't redownload a file to fix it.

You're fine to hit skip, and play as normal. If it complains about any _other_ files, then it's worth forcing an update.

**Comment by juhoyhoy** [comment]
Did as you said, hit skip and tried to launch, after the updater closed itself something launched for a split second and then immediately closed right after, i've tried to launch several times all with the same result.
_edit_ i believe its starting the "eldorado" application, but it closing right after it starts up

**Comment by scooterpsu** [comment]
What you have at that point is an issue with the game, not the launcher. Be sure to follow whatever guide that got you this far.

**Comment by juhoyhoy** [comment]
hmm... i'll try reinstalling, thanks for the help
