### ISSUE TITLE
Parsing doubles can fail because of Culture

### ISSUE THREAD

**Issue by msarilar** [FishPhd/DewritoUpdater#35]
Use InvariantCulture to avoid errors when parsing doubles on a computer that uses a culture which considers doubles should use commas instead of dots. The failure raises an unhandled exception that brutally crashes the software.

Example:

`VAL.Value = Convert.ToDouble(Cfg.configFile["VoIP.VoiceActivationLevel"], CultureInfo.InvariantCulture);`

**Comment by NoShotz** [comment]
the thing is, the game reads the .'s from the config this program generates not ,'s

**Comment by msarilar** [comment]
That would be precisely the issue ; the french culture (for instance) expects a comma when parsing the number and it finds a dot. When it will try to write a double (when saving the config), it will use a comma instead of a dot. 

By specifying the Invariant Culture, the software will expect a dot when parsing and write a dot when saving ; regardless of the computer's current culture.

Writing example to mirror the reading example I posted:

`Cfg.SetVariable("Camera.FOV", Convert.ToString(Fov.Value, CultureInfo.InvariantCulture), ref Cfg.configFile);`

**Comment by FishPhd** [comment]
Added in bb242e6aac498875f57aad862d8024e8d9516d35
