### ISSUE TITLE
0.5.0.2 Cannot locate eldorado.exe

### ISSUE THREAD

**Issue by Ghost-Mop** [FishPhd/DewritoUpdater#42]
"Cfg Load Complete
You have the latest version: 0.5.0.2
Cannot locate eldorado.exe. Are you running in the right location?"

Is there a solution for this/can I get a new copy of the eldorado.exe file?

**Comment by scooterpsu** [comment]
Are you putting the updater in the same folder as eldorado.exe?

**Comment by Ghost-Mop** [comment]
All the files are in C:\Halo Online

**Comment by Ghost-Mop** [comment]
There's not even an eldorado.exe in the 0.5.0.2 copy of the files

**Comment by scooterpsu** [comment]
This launcher doesn't give you the game. You add the launcher _to_ the game directory.

**Comment by Ghost-Mop** [comment]
How big is your directory's folder in gb?

**Comment by NoShotz** [comment]
like 2.6gb or around that

**Comment by NoShotz** [comment]
did you get it from here?   https://www.reddit.com/r/HaloOnline/comments/423you/0501/?ref=search_posts

**Comment by Ghost-Mop** [comment]
downloaded the full game twice, once from torrent and once from mega. then added in the manual download files because the updater was consistently failing me all day today.

my directory says 3.16gb

**Comment by NoShotz** [comment]
well the game should have eldorado.exe if you got it from the link i sent you

**Comment by NoShotz** [comment]
http://i.imgur.com/5OV2aT1.png

**Comment by Ghost-Mop** [comment]
![the torrent](https://cloud.githubusercontent.com/assets/17790105/13716736/9d115e2c-e7a2-11e5-9a1d-e891301773ea.png)

it's just plain old not there

**Comment by NoShotz** [comment]
thats not how it should be, download it fresh from one of the full game download links here,   https://www.reddit.com/r/HaloOnline/comments/423you/0501/?ref=search_posts

**Comment by Ghost-Mop** [comment]
REdownloading from the torrent for speed reasons... still only about 2mb/s. I'll update you when it's done.

**Comment by Ghost-Mop** [comment]
How did you download _your _copy

**Comment by Ghost-Mop** [comment]
Torrent has just finished downloading. Extracting to C:\Halo_Online

**Comment by Ghost-Mop** [comment]
works now. no idea what happened to cause the problem initially.
