### ISSUE TITLE
dewrito_prefs.cfg is constantly being overwritten with default settings

### ISSUE THREAD

**Issue by rhlabsuk** [FishPhd/DewritoUpdater#43]
I tried customising my armour in-game and changed the default launcher URL, when I reloaded the game it had all reverted to the default options in the config. Is this a bug or am I missing a setting in the options?

I'm running the very latest version of the launcher as of writing this.

**Comment by NoShotz** [comment]
This is known, and is fixed in the unreleased version of the updater, but for now, set your prefs to read only when you set your armor. The updater is also being dropped in 0.6.0, and is replaced with ingame stuff for armor changing, ect

**Comment by rhlabsuk** [comment]
@NoShotz Awesome, thanks for the quick reply :)

**Comment by FishPhd** [comment]
Sike
