### ISSUE TITLE
Launcher Fails to Download DewritoLauncher.exe

### ISSUE THREAD

**Issue by Kyrluckechuck** [FishPhd/DewritoUpdater#7]
Update fails for DewritoUpdater.exe coming from 0.4.6

It also corrupts my actual DewritoUpdater.exe. Luckily it leaves the DewritoUpdater.exe.old

If it helps, the downloaded DewritoUpdater.exe always gets between 600kb-950kb.

**Comment by Kyrluckechuck** [comment]
After the 9th attempt, it updated. So it fails often.

**Comment by Ricadan** [comment]
I'm getting the same thing, except it fails immediately with no download, so I'm not sure if more attempts will solve it.

This is the message I get from the launcher
Error: The underlying connection was closed: The connection was closed unexpectedly.

**Comment by FishPhd** [comment]
If you are having trouble connecting to the update server forward ports 80 and 81 and try again
